# Ticker - Tps logistics for Skript.

# The version is to help determine which version this config is. Please don't modify this value.
version: "1.0.0"

# Print additional information in the console. The developers of Ticker may ask you to enable this when reporting an error.
debug: false

# Broadcast all the syntax that didn't register to the console.
NotRegisteredSyntax: false

# Should Ticker wait a few seconds before starting the server tracking progress.
# The server typically lags when it first starts up due to all the plugin loading.
# This makes the average tps more accurate.
ServerStartupQueue: true

# Converts the Enum's into proper english enums like `FADE_TYPE` will be `fade type` or `fading type`
#as defined in the english.lang of the jar. (Which can be edited, they parent aliases parsing)
UseEnglishEnums: true

# Disables the message saying Ticker was enabled.
DisableRegisteredInfo: false